#!/usr/bin/php
<?php
/**
 * @author Kornel Lugosi (Coornail)
 *
 * pre-comit git hook for check php files syntactically and analyze statically
 * Originally from: http://phpadvent.org/2008/dont-commit-that-error-by-travis-swicegood (but reworked almost fully)
 */


$output = array();
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

exec("git diff-index --cached --name-only {$against}", $output);

$filename_pattern = '/\.(php|engine|theme|install|inc|module|test)$/';

foreach ($output as $file) {
  if (!preg_match($filename_pattern, $file)) {
    continue;
  }

  echo '[*] :: '. escapeshellarg($file) . "\n";
  exec('~/shellscript/phpcheck '. escapeshellarg($file), $output, $exit_status);
  foreach ($output as $line) {
    echo $line ."\n";
  }

  if ($exit_status != 0) {
    exit(1);
  }
}

